<?php

use Illuminate\Support\Facades\Route;

// ── Package Data (static, to be replaced by DB later) ──
$packagesData = [

    'gili-islands' => [
        'slug'          => 'gili-islands',
        'name'          => 'Gili Islands Getaway',
        'category'      => 'Lombok',
        'badge_class'   => 'pkg-badge-lombok',
        'popular_badge' => null,
        'location'      => 'Gili Trawangan, Meno & Air',
        'duration'      => '3H / 2M',
        'min_pax'       => 2,
        'language'      => 'Indonesia / Inggris',
        'rating'        => 4.9,
        'reviews'       => 128,
        'price_display' => 'Rp 1,8 Jt',
        'price_raw'     => 1800000,
        'hero_img'      => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1800&q=85',
        'desc'          => 'Nikmati keindahan tiga Gili yang ikonik — Trawangan, Meno, dan Air.',
        'desc_long'     => 'Gili Islands Getaway adalah paket wisata premium yang mengajak Anda menjelajahi pesona tiga Gili yang ikonik di Lombok — Gili Trawangan, Gili Meno, dan Gili Air. Selama 3 hari 2 malam, nikmati pantai berpasir putih yang memukau, air laut kristal yang jernih, dan kehidupan bawah laut yang kaya warna. Paket ini dirancang untuk pasangan, keluarga kecil, maupun teman-teman yang ingin liburan santai namun berkesan. Tidak ada kendaraan bermotor di Gili — hanya cidomo (kereta kuda), sepeda, dan ketenangan alam.',
        'map_embed'     => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d31625.408!2d116.105!3d-8.352!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dcdb5ab6a946e4b%3A0x5f49e5ca9c2e16a8!2sGili%20Trawangan!5e0!3m2!1sen!2sid!4v1',
        'gallery'       => [
            'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&q=80',
            'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&q=80',
            'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80',
            'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
            'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=1200&q=80',
        ],
        'highlights'    => [
            ['icon' => 'fas fa-hotel', 'title' => 'Hotel Bintang 3', 'sub' => 'Penginapan nyaman di tepi pantai dengan fasilitas lengkap'],
            ['icon' => 'fas fa-fish', 'title' => 'Snorkeling', 'sub' => 'Peralatan snorkeling lengkap termasuk dalam paket'],
            ['icon' => 'fas fa-ship', 'title' => 'Boat Transfer', 'sub' => 'Transportasi speedboat PP dari dermaga Bangsal'],
            ['icon' => 'fas fa-user-tie', 'title' => 'Tour Guide', 'sub' => 'Pemandu wisata profesional berpengalaman'],
            ['icon' => 'fas fa-utensils', 'title' => 'Makan Pagi', 'sub' => 'Sarapan tersedia setiap pagi di hotel'],
            ['icon' => 'fas fa-bicycle', 'title' => 'Sewa Sepeda', 'sub' => 'Sepeda gratis untuk keliling pulau'],
        ],
        'itinerary'     => [
            [
                'day'        => 1,
                'title'      => 'Tiba di Gili Trawangan',
                'desc'       => 'Penjemputan dari Bandara Lombok atau hotel di Mataram, lalu perjalanan menuju Bangsal.',
                'activities' => [
                    'Penjemputan & transfer ke Pelabuhan Bangsal',
                    'Naik speedboat ke Gili Trawangan',
                    'Check-in hotel & makan siang',
                    'Snorkeling sore di spot terumbu karang',
                    'Sunset di pantai barat + makan malam seafood',
                ],
                'note' => 'Penjemputan pukul 08.00 dari Bandara Lombok / Hotel di Mataram',
            ],
            [
                'day'        => 2,
                'title'      => 'Island Hopping Tiga Gili',
                'desc'       => 'Hari penuh petualangan menjelajahi Gili Meno dan Gili Air dengan speedboat carter.',
                'activities' => [
                    'Sarapan di hotel',
                    'Island hopping ke Gili Meno — Turtle Point Snorkeling',
                    'Mampir ke Gili Air — pantai tenang & kuliner lokal',
                    'Kembali ke Gili Trawangan sore hari',
                    'Free evening — pilih antara sunset bar atau spa',
                ],
            ],
            [
                'day'        => 3,
                'title'      => 'Hari Terakhir & Kembali',
                'desc'       => 'Nikmati pagi santai sebelum check-out dan perjalanan pulang.',
                'activities' => [
                    'Sarapan terakhir di hotel',
                    'Check-out & simpan koper di hotel',
                    'Bebas jelajah pantai atau belanja souvenir',
                    'Speedboat kembali ke Bangsal',
                    'Transfer ke Bandara / Mataram',
                ],
                'note' => 'Speedboat ke Bangsal tersedia pukul 11.00 dan 14.00',
            ],
        ],
        'includes'      => [
            'Transportasi AC dari/ke Bandara Lombok',
            'Tiket speedboat PP (Bangsal ↔ Gili Trawangan)',
            'Akomodasi 2 malam Hotel Bintang 3',
            'Sarapan 2x di hotel',
            'Island hopping 3 Gili (speedboat charter)',
            'Peralatan snorkeling lengkap',
            'Tour Guide profesional',
            'Sewa sepeda 1 hari',
            'Air mineral selama perjalanan',
        ],
        'excludes'      => [
            'Tiket pesawat menuju Lombok',
            'Makan siang & makan malam (kecuali yang disebutkan)',
            'Biaya wisata tambahan di luar itinerary',
            'Tips untuk guide & porter',
            'Pengeluaran pribadi',
            'Travel insurance',
        ],
        'notes'         => [
            'Jadwal dapat berubah sesuai kondisi cuaca dan gelombang laut.',
            'Minimal booking 2 orang dewasa.',
            'Pembayaran DP minimal 30% untuk konfirmasi booking.',
        ],
        'review_list'   => [
            ['name' => 'Rina Kartika', 'date' => 'Maret 2025', 'rating' => 5, 'text' => 'Paket yang sangat luar biasa! Guide-nya ramah dan profesional. Pemandangan Gili sungguh memukau, pantainya bersih dan airnya jernih sekali. Pasti akan balik lagi!'],
            ['name' => 'Budi Santoso', 'date' => 'Februari 2025', 'rating' => 5, 'text' => 'Sangat puas dengan pelayanan WestTravel. Semua sesuai itinerary, hotel oke, snorkeling seru banget. Worth every penny!'],
            ['name' => 'Maya Dewi', 'date' => 'Januari 2025', 'rating' => 5, 'text' => 'Ini kali kedua saya pakai jasa WestTravel, dan selalu memuaskan. Gili Trawangan memang surga! Highly recommended.'],
        ],
        'related'       => [
            ['slug' => 'pendakian-rinjani', 'name' => 'Pendakian Rinjani', 'category' => 'Lombok', 'badge_class' => 'pkg-badge-lombok', 'duration' => '4H / 3M', 'price' => 'Rp 2,5 Jt', 'img' => 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=700&q=80', 'desc' => 'Taklukkan puncak Gunung Rinjani 3.726 mdpl dan Segara Anak.'],
            ['slug' => 'lombok-lengkap', 'name' => 'Lombok Lengkap Tour', 'category' => 'Lombok', 'badge_class' => 'pkg-badge-lombok', 'duration' => '5H / 4M', 'price' => 'Rp 3,2 Jt', 'img' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=700&q=80', 'desc' => 'Jelajahi Mandalika, Desa Sade, hingga tenun Sukarara.'],
            ['slug' => 'pulau-moyo', 'name' => 'Pulau Moyo Retreat', 'category' => 'Sumbawa', 'badge_class' => 'pkg-badge-sumbawa', 'duration' => '3H / 2M', 'price' => 'Rp 3,5 Jt', 'img' => 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=700&q=80', 'desc' => 'Destinasi eksklusif Pulau Moyo dengan glamping dan diving.'],
        ],
    ],

    'pendakian-rinjani' => [
        'slug'          => 'pendakian-rinjani',
        'name'          => 'Pendakian Rinjani',
        'category'      => 'Lombok',
        'badge_class'   => 'pkg-badge-lombok',
        'popular_badge' => '🔥 Terpopuler',
        'location'      => 'Gunung Rinjani, Lombok',
        'duration'      => '4H / 3M',
        'min_pax'       => 2,
        'language'      => 'Indonesia / Inggris',
        'rating'        => 5.0,
        'reviews'       => 94,
        'price_display' => 'Rp 2,5 Jt',
        'price_raw'     => 2500000,
        'hero_img'      => 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1800&q=85',
        'desc'          => 'Taklukkan puncak Gunung Rinjani 3.726 mdpl. Jelajahi Segara Anak dan danau kawah yang memukau.',
        'desc_long'     => 'Paket Pendakian Rinjani adalah pengalaman petualangan sejati yang mengajak Anda menaklukkan Gunung Rinjani, salah satu gunung berapi aktif tertinggi di Indonesia (3.726 mdpl). Selama 4 hari 3 malam, Anda akan melewati jalur-jalur spektakuler, berkemah di ketinggian, dan menyaksikan keajaiban Segara Anak — danau kawah yang memukau dengan air biru kehijauan. Paket ini mencakup porter, tenda premium, dan pemandu berpengalaman yang memastikan keselamatan dan kenyamanan perjalanan Anda.',
        'map_embed'     => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d62760.28!2d116.465!3d-8.412!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dcda43c4ace7b55%3A0x5f94a7b3ca5a91d9!2sMount%20Rinjani!5e0!3m2!1sen!2sid!4v1',
        'gallery'       => [
            'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
            'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80',
            'https://images.unsplash.com/photo-1478827536114-da961b7f86d2?w=1200&q=80',
            'https://images.unsplash.com/photo-1551632811-561732d1e306?w=1200&q=80',
            'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&q=80',
        ],
        'highlights'    => [
            ['icon' => 'fas fa-campground', 'title' => 'Tenda Dome Premium', 'sub' => 'Tenda dome 4 musim yang nyaman dan tahan angin'],
            ['icon' => 'fas fa-hands-helping', 'title' => 'Porter Profesional', 'sub' => 'Porter berpengalaman membawa perlengkapan Anda'],
            ['icon' => 'fas fa-utensils', 'title' => 'Makan 3x/Hari', 'sub' => 'Menu lezat disiapkan oleh cook profesional di camp'],
            ['icon' => 'fas fa-first-aid', 'title' => 'Rescue Kit Lengkap', 'sub' => 'Perlengkapan P3K dan rescue kit tersedia'],
            ['icon' => 'fas fa-user-shield', 'title' => 'Guide Berlisensi', 'sub' => 'Pemandu resmi berlisensi BNSP & berpengalaman'],
            ['icon' => 'fas fa-mountain', 'title' => 'Puncak 3.726 mdpl', 'sub' => 'Saksikan sunrise spektakuler dari puncak Rinjani'],
        ],
        'itinerary'     => [
            ['day' => 1, 'title' => 'Sembalun — Pos 3', 'desc' => 'Start dari Sembalun, trekking melewati padang savana yang luas dan cantik.', 'activities' => ['Briefing & persiapan di basecamp Sembalun', 'Trek melewati padang savana (3-4 jam)', 'Istirahat di Pos 2 (makan siang)', 'Lanjut trek ke Pos 3 (2-3 jam)', 'Makan malam & bermalam di Pos 3'], 'note' => 'Start trekking pukul 07.00 WITA dari basecamp'],
            ['day' => 2, 'title' => 'Puncak Rinjani & Segara Anak', 'desc' => 'Pagi buta summit attack ke puncak, lalu turun menuju Segara Anak.', 'activities' => ['Bangun 01.00 — Summit attack (4-5 jam)', 'Sunrise spektakuler di Puncak 3.726 mdpl', 'Turun ke Pelawangan Sembalun', 'Turun menuju Danau Segara Anak (3 jam)', 'Mandi air panas alami di sumber hot spring', 'Camp di tepi Segara Anak']],
            ['day' => 3, 'title' => 'Segara Anak — Senaru', 'desc' => 'Pagi eksplorasi danau, siang trekking keluar via jalur Senaru.', 'activities' => ['Sarapan sambil menikmati view Segara Anak', 'Eksplorasi danau & air terjun Sendang Gile mini', 'Trek naik ke Pelawangan Senaru (3 jam)', 'Trek turun via Senaru (4-5 jam)', 'Tiba di basecamp Senaru — mandi & makan malam']],
            ['day' => 4, 'title' => 'Senaru — Pulang', 'desc' => 'Sarapan dan transfer kembali ke Mataram atau Bandara.', 'activities' => ['Sarapan & bersih-bersih di basecamp', 'Transfer ke Mataram / Bandara Lombok', 'Sertifikat pendakian'], 'note' => 'Estimasi tiba Mataram pukul 14.00 WITA'],
        ],
        'includes'      => ['Transportasi dari Mataram PP', 'Semua biaya masuk TNGR', 'Guide profesional berlisensi', 'Porter (1 porter per 2 peserta)', 'Tenda dome premium', 'Sleeping bag (-10°C)', 'Makan 3x/hari + snack', 'Rescue kit & obat-obatan dasar', 'Sertifikat pendakian'],
        'excludes'      => ['Tiket pesawat', 'Penginapan di Mataram (jika perlu)', 'Tips guide & porter', 'Perlengkapan mendaki pribadi (sepatu, jaket, dll)', 'Biaya darurat medis', 'Pengeluaran pribadi'],
        'notes'         => ['Wajib kondisi fisik yang prima. Kami sarankan olahraga cardio 1 bulan sebelum pendakian.', 'Bawa sepatu trekking/gunung. Tidak diperkenankan pakai sandal.', 'Musim terbaik pendakian: April — Oktober. Rinjani tutup Nov–Maret.'],
        'review_list'   => [
            ['name' => 'Arif Rahman', 'date' => 'April 2025', 'rating' => 5, 'text' => 'Pengalaman paling mengesankan dalam hidup! Guide-nya super profesional dan sabar. Sunrise dari puncak Rinjani = tak terlupakan seumur hidup!'],
            ['name' => 'Siti Nurbaya', 'date' => 'Maret 2025', 'rating' => 5, 'text' => 'Pertama kali naik gunung dan pilih WestTravel. Keputusan terbaik! Guide sangat membantu dan makanan di camp enak sekali.'],
            ['name' => 'Dedi Firmansyah', 'date' => 'Februari 2025', 'rating' => 5, 'text' => 'Segara Anak dan hot spring-nya bikin speechless. WestTravel = terpercaya, profesional, dan harga sebanding kualitas!'],
        ],
        'related'       => [
            ['slug' => 'gili-islands', 'name' => 'Gili Islands Getaway', 'category' => 'Lombok', 'badge_class' => 'pkg-badge-lombok', 'duration' => '3H / 2M', 'price' => 'Rp 1,8 Jt', 'img' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=700&q=80', 'desc' => 'Nikmati keindahan tiga Gili yang ikonik dan snorkeling.'],
            ['slug' => 'lombok-lengkap', 'name' => 'Lombok Lengkap Tour', 'category' => 'Lombok', 'badge_class' => 'pkg-badge-lombok', 'duration' => '5H / 4M', 'price' => 'Rp 3,2 Jt', 'img' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=700&q=80', 'desc' => 'Paket lengkap menjelajahi seluruh pesona Lombok.'],
            ['slug' => 'sumbawa-paradise', 'name' => 'Sumbawa Hidden Paradise', 'category' => 'Sumbawa', 'badge_class' => 'pkg-badge-sumbawa', 'duration' => '4H / 3M', 'price' => 'Rp 2,8 Jt', 'img' => 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=700&q=80', 'desc' => 'Temukan keindahan Sumbawa yang masih tersembunyi.'],
        ],
    ],

    'lombok-lengkap' => [
        'slug' => 'lombok-lengkap', 'name' => 'Lombok Lengkap Tour', 'category' => 'Lombok', 'badge_class' => 'pkg-badge-lombok', 'popular_badge' => null,
        'location' => 'Lombok', 'duration' => '5H / 4M', 'min_pax' => 2, 'language' => 'Indonesia / Inggris',
        'rating' => 4.8, 'reviews' => 71, 'price_display' => 'Rp 3,2 Jt', 'price_raw' => 3200000,
        'hero_img' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1800&q=85',
        'desc' => 'Paket lengkap menjelajahi Lombok — Mandalika, Desa Sade, Air Terjun Sendang Gile, hingga tenun Sukarara.',
        'desc_long' => 'Lombok Lengkap Tour adalah paket wisata komprehensif yang mengajak Anda menjelajahi seluruh kekayaan alam dan budaya Lombok dalam 5 hari 4 malam. Dari kemegahan KEK Mandalika yang modern, kearifan lokal Desa Sade yang masih terjaga, kesegaran Air Terjun Sendang Gile di kaki Gunung Rinjani, hingga keindahan tenun tradisional Sukarara — semua dirangkum dalam satu paket yang menyeluruh dan berkesan.',
        'map_embed' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d250703.17!2d116.105!3d-8.583!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dcdb5e1e0d5d44f%3A0x5b437e40f97e4321!2sMataram%2C+West+Nusa+Tenggara!5e0!3m2!1sen!2sid!4v1',
        'gallery' => ['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&q=80','https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&q=80','https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80','https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80'],
        'highlights' => [['icon'=>'fas fa-hotel','title'=>'Hotel Bintang 4','sub'=>'Akomodasi nyaman di pusat kota Mataram'],['icon'=>'fas fa-car','title'=>'AC Vehicle','sub'=>'Kendaraan ber-AC full hari selama tour'],['icon'=>'fas fa-ticket-alt','title'=>'Semua Entry Ticket','sub'=>'Tiket masuk semua destinasi sudah termasuk'],['icon'=>'fas fa-camera','title'=>'Dokumentasi','sub'=>'Fotografer profesional menemani perjalanan']],
        'itinerary' => [
            ['day'=>1,'title'=>'Tiba di Lombok — Mataram & Sekitarnya','desc'=>'Jelajahi kota Mataram dan sekitarnya.','activities'=>['Penjemputan di Bandara Lombok','Pura Meru & Mayura Water Palace','Pasar Kerajinan Sayang-Sayang','Makan malam khas Lombok','Check-in Hotel Bintang 4']],
            ['day'=>2,'title'=>'Senggigi & Pantai Barat','desc'=>'Jelajahi kawasan pesisir barat Lombok.','activities'=>['Sarapan di hotel','Pantai Senggigi & Batu Bolong Temple','Snorkeling di Pantai Selong Belanak','Sunset di Pantai Mawun','Makan malam seafood']],
            ['day'=>3,'title'=>'Mandalika & Selatan Lombok','desc'=>'Kunjungi KEK Mandalika dan pantai-pantai selatan.','activities'=>['Sirkuit Mandalika (Indonesia MotoGP Circuit)','Pantai Kuta Lombok','Pantai Tanjung Aan','Bukit Merese','Desa Sade — Budaya Sasak']],
            ['day'=>4,'title'=>'Utara Lombok & Air Terjun','desc'=>'Hari eksplorasi utara Lombok yang hijau.','activities'=>['Desa Senaru','Air Terjun Sendang Gile','Air Terjun Tiu Kelep','Desa Sukarara — Tenun Tradisional','Bebas sore hari']],
            ['day'=>5,'title'=>'Gili Nanggu & Pulang','desc'=>'Pagi santai di Gili Nanggu sebelum kembali.','activities'=>['Sarapan & check-out','Island trip ke Gili Nanggu (2 jam)','Snorkeling penyu hijau','Kembali & transfer ke Bandara'],'note'=>'Estimasi transfer ke bandara pukul 14.00'],
        ],
        'includes' => ['Penjemputan & antar di Bandara','Akomodasi 4 malam Hotel Bintang 4','Sarapan 4x','Kendaraan AC full day','Semua tiket masuk destinasi','Snorkeling equipment (Selong Belanak & Gili Nanggu)','Tour Guide profesional','Fotografer (1 hari)','Air mineral'],
        'excludes' => ['Tiket pesawat','Makan siang & malam (kecuali yang disebutkan)','Tips guide & driver','Pengeluaran pribadi','Travel insurance'],
        'notes' => ['Urutan destinasi dapat berubah sesuai kondisi.','Minimal 2 orang dewasa.'],
        'review_list' => [
            ['name'=>'Hendra Kusuma','date'=>'April 2025','rating'=>5,'text'=>'5 hari di Lombok bersama WestTravel sangat berkesan! Semua destinasi keren, guide-nya seru dan informatif. Lombok memang juara!'],
            ['name'=>'Fira Amelia','date'=>'Maret 2025','rating'=>5,'text'=>'Paket lengkap banget, worth it! Terutama Desa Sade dan tenun Sukarara, pengalaman budaya yang tidak ada di tempat lain.'],
        ],
        'related' => [
            ['slug'=>'gili-islands','name'=>'Gili Islands Getaway','category'=>'Lombok','badge_class'=>'pkg-badge-lombok','duration'=>'3H / 2M','price'=>'Rp 1,8 Jt','img'=>'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=700&q=80','desc'=>'Nikmati keindahan tiga Gili yang ikonik.'],
            ['slug'=>'pendakian-rinjani','name'=>'Pendakian Rinjani','category'=>'Lombok','badge_class'=>'pkg-badge-lombok','duration'=>'4H / 3M','price'=>'Rp 2,5 Jt','img'=>'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=700&q=80','desc'=>'Taklukkan puncak Gunung Rinjani 3.726 mdpl.'],
            ['slug'=>'pulau-moyo','name'=>'Pulau Moyo Retreat','category'=>'Sumbawa','badge_class'=>'pkg-badge-sumbawa','duration'=>'3H / 2M','price'=>'Rp 3,5 Jt','img'=>'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=700&q=80','desc'=>'Glamping eksklusif dan diving di Pulau Moyo.'],
        ],
    ],

    'sumbawa-paradise' => [
        'slug'=>'sumbawa-paradise','name'=>'Sumbawa Hidden Paradise','category'=>'Sumbawa','badge_class'=>'pkg-badge-sumbawa','popular_badge'=>null,
        'location'=>'Sumbawa Besar','duration'=>'4H / 3M','min_pax'=>2,'language'=>'Indonesia',
        'rating'=>4.7,'reviews'=>43,'price_display'=>'Rp 2,8 Jt','price_raw'=>2800000,
        'hero_img'=>'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1800&q=85',
        'desc'=>'Temukan Sumbawa yang masih perawan — Pantai Maluk, Teluk Saleh, dan budaya Mbojo yang autentik.',
        'desc_long'=>'Sumbawa Hidden Paradise mengajak Anda menjelajahi pesona Sumbawa yang belum banyak terjamah. Selama 4 hari 3 malam, rasakan keindahan pantai-pantai tersembunyi, jelajahi kedalaman Teluk Saleh yang menakjubkan, dan mengenal budaya Mbojo yang masih terjaga keasliannya. Sumbawa adalah destinasi bagi jiwa-jiwa petualang yang mencari keautentikan.',
        'map_embed'=>'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d125321.21!2d117.412!3d-8.489!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dcc3c8dd50e9c4d%3A0x2f54e98fb4c7b9d7!2sSumbawa%20Regency!5e0!3m2!1sen!2sid!4v1',
        'gallery'=>['https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&q=80','https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80','https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=1200&q=80','https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&q=80'],
        'highlights'=>[['icon'=>'fas fa-home','title'=>'Penginapan Lokal','sub'=>'Menginap di penginapan autentik khas Sumbawa'],['icon'=>'fas fa-ship','title'=>'Boat Charter','sub'=>'Perahu sewaan eksklusif menjelajahi Teluk Saleh'],['icon'=>'fas fa-fish','title'=>'Snorkeling','sub'=>'Spot snorkeling terumbu karang yang masih terjaga'],['icon'=>'fas fa-user-tie','title'=>'Guide Lokal','sub'=>'Pemandu asli Sumbawa yang mengenal daerah dengan baik']],
        'itinerary'=>[
            ['day'=>1,'title'=>'Tiba di Sumbawa','desc'=>'Penjemputan dan mengenal kota Sumbawa Besar.','activities'=>['Penjemputan di Bandara Sultan Muhammad Kaharuddin','Keraton Sumbawa (Dalam Loka)','Masjid Agung Sumbawa','Check-in & makan malam khas Sumbawa']],
            ['day'=>2,'title'=>'Teluk Saleh & Pulau Moyo','desc'=>'Eksplorasi Teluk Saleh dengan boat charter sehari penuh.','activities'=>['Sarapan & berangkat ke dermaga','Jelajah Teluk Saleh dengan perahu','Snorkeling di spot terumbu karang','Spot melihat hiu paus (seasonal)','Sunset di pulau kecil di tengah teluk']],
            ['day'=>3,'title'=>'Pantai Maluk & Sekitarnya','desc'=>'Pantai-pantai barat Sumbawa yang spektakuler.','activities'=>['Sarapan & berangkat ke Maluk','Pantai Maluk — spot surfing kelas dunia','Pantai Sekongkang','Pantai Tropical','Mampir ke komunitas nelayan lokal']],
            ['day'=>4,'title'=>'Kembali & Budaya Mbojo','desc'=>'Pagi mengenal budaya, siang pulang.','activities'=>['Pasar tradisional Sumbawa','Kerajinan tangan khas Mbojo','Transfer ke Bandara'],['note'=>'Penerbangan dari Bandara Sumbawa']],
        ],
        'includes'=>['Penjemputan & antar bandara','Akomodasi 3 malam','Sarapan 3x','Kendaraan AC','Boat charter Teluk Saleh (full day)','Snorkeling equipment','Guide lokal','Air mineral'],
        'excludes'=>['Tiket pesawat ke Sumbawa','Makan siang & malam','Tips','Pengeluaran pribadi','Travel insurance'],
        'notes'=>['Penerbangan ke Sumbawa biasanya transit di Lombok.','Bawa tabir surya dan pakaian renang.'],
        'review_list'=>[
            ['name'=>'Yanto Pribadi','date'=>'April 2025','rating'=>5,'text'=>'Sumbawa benar-benar hidden gem! Teluk Saleh luar biasa, snorkeling terbaik yang pernah saya lakukan. WestTravel sangat amanah.'],
            ['name'=>'Lina Marlina','date'=>'Maret 2025','rating'=>4,'text'=>'Pengalaman yang berbeda dari Bali atau Lombok. Sumbawa masih alami banget. Guide lokalnya super ramah dan informatif.'],
        ],
        'related'=>[
            ['slug'=>'pulau-moyo','name'=>'Pulau Moyo Retreat','category'=>'Sumbawa','badge_class'=>'pkg-badge-sumbawa','duration'=>'3H / 2M','price'=>'Rp 3,5 Jt','img'=>'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=700&q=80','desc'=>'Glamping dan diving di Pulau Moyo yang eksklusif.'],
            ['slug'=>'gili-islands','name'=>'Gili Islands Getaway','category'=>'Lombok','badge_class'=>'pkg-badge-lombok','duration'=>'3H / 2M','price'=>'Rp 1,8 Jt','img'=>'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=700&q=80','desc'=>'Nikmati keindahan tiga Gili yang ikonik.'],
            ['slug'=>'pendakian-rinjani','name'=>'Pendakian Rinjani','category'=>'Lombok','badge_class'=>'pkg-badge-lombok','duration'=>'4H / 3M','price'=>'Rp 2,5 Jt','img'=>'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=700&q=80','desc'=>'Taklukkan puncak Gunung Rinjani yang legendaris.'],
        ],
    ],

    'pulau-moyo' => [
        'slug'=>'pulau-moyo','name'=>'Pulau Moyo Retreat','category'=>'Sumbawa','badge_class'=>'pkg-badge-sumbawa','popular_badge'=>null,
        'location'=>'Pulau Moyo, Sumbawa','duration'=>'3H / 2M','min_pax'=>2,'language'=>'Indonesia / Inggris',
        'rating'=>5.0,'reviews'=>62,'price_display'=>'Rp 3,5 Jt','price_raw'=>3500000,
        'hero_img'=>'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=1800&q=85',
        'desc'=>'Pulau Moyo — destinasi eksklusif pernah dikunjungi Lady Diana. Air terjun, diving, dan hutan tropis memukau.',
        'desc_long'=>'Pulau Moyo Retreat menghadirkan pengalaman liburan eksklusif di pulau terpencil yang pernah menjadi destinasi favorit Lady Diana dan berbagai selebriti dunia. Terletak di lepas pantai utara Sumbawa, Pulau Moyo adalah surga tersembunyi dengan hutan tropis yang lebat, air terjun tersembunyi yang menakjubkan, dan perairan jernih yang menjadi rumah bagi beragam kehidupan laut. Glamping mewah di tepi pantai dan diving di spot-spot premium adalah daya tarik utama paket ini.',
        'map_embed'=>'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d31421.08!2d117.616!3d-8.271!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dcc2b72bcfebec5%3A0x7b1e2e3f4a5b6c7d!2sMoyo%20Island!5e0!3m2!1sen!2sid!4v1',
        'gallery'=>['https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=1200&q=80','https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80','https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&q=80','https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&q=80'],
        'highlights'=>[['icon'=>'fas fa-campground','title'=>'Glamping Premium','sub'=>'Tenda mewah di tepi pantai dengan pemandangan spektakuler'],['icon'=>'fas fa-swimmer','title'=>'Diving','sub'=>'Diving di spot-spot terbaik dengan terumbu karang pristine'],['icon'=>'fas fa-tint','title'=>'Air Terjun Tersembunyi','sub'=>'Trekking ke air terjun alami di dalam hutan tropis'],['icon'=>'fas fa-sun','title'=>'Sunset Tour','sub'=>'Perahu sunset cruise mengelilingi pulau']],
        'itinerary'=>[
            ['day'=>1,'title'=>'Tiba di Pulau Moyo','desc'=>'Penyeberangan dari Sumbawa dan check-in glamping.','activities'=>['Transfer dari Sumbawa ke dermaga','Penyeberangan speedboat ke Pulau Moyo','Check-in glamping premium','Snorkeling sore hari','Makan malam BBQ tepi pantai']],
            ['day'=>2,'title'=>'Petualangan Penuh','desc'=>'Hari penuh aktivitas — air terjun, diving, dan sunset.','activities'=>['Sarapan sunrise di tepi pantai','Trekking ke Air Terjun Mata Jitu','Diving 2 dive di spot pilihan','Istirahat siang — hammock time','Sunset boat trip mengelilingi pulau','BBQ dinner di bawah bintang']],
            ['day'=>3,'title'=>'Pagi Santai & Pulang','desc'=>'Nikmati pagi terakhir sebelum kembali ke Sumbawa.','activities'=>['Sarapan & bebas menikmati pantai','Snorkeling terakhir di house reef','Check-out & packing','Speedboat kembali ke Sumbawa','Transfer ke Bandara'],'note'=>'Speedboat kembali tersedia pukul 10.00 dan 13.00'],
        ],
        'includes'=>['Speedboat PP ke Pulau Moyo','Glamping 2 malam (tenda premium)','Semua makan (sarapan, makan siang, makan malam)','2x diving (equipment included)','Snorkeling equipment','Trekking ke air terjun','Sunset boat trip','Air mineral & minuman non-alkohol'],
        'excludes'=>['Tiket pesawat ke Sumbawa','Transfer dari/ke Bandara Sumbawa','Minuman beralkohol','Tips','Pengeluaran pribadi'],
        'notes'=>['Pulau Moyo adalah kawasan konservasi — dilarang merusak lingkungan.','Bawa senter untuk malam hari.','Tidak ada sinyal HP di sebagian besar pulau.'],
        'review_list'=>[
            ['name'=>'Rizal Fadhli','date'=>'April 2025','rating'=>5,'text'=>'Pulau Moyo = paradise on earth. Glamping-nya mewah tapi tetap menyatu dengan alam. Diving di sana terbaik yang pernah saya rasakan!'],
            ['name'=>'Dewi Puspita','date'=>'Maret 2025','rating'=>5,'text'=>'Honeymoon terbaik! Romantis, tenang, dan indah sekali. Air terjun Mata Jitu memukau. Terima kasih WestTravel!'],
            ['name'=>'Anton Wibowo','date'=>'Februari 2025','rating'=>5,'text'=>'Fully disconnected dari dunia maya — dan itu yang terbaik! Malam berbintang di tepi pantai Pulau Moyo tidak tergantikan.'],
        ],
        'related'=>[
            ['slug'=>'sumbawa-paradise','name'=>'Sumbawa Hidden Paradise','category'=>'Sumbawa','badge_class'=>'pkg-badge-sumbawa','duration'=>'4H / 3M','price'=>'Rp 2,8 Jt','img'=>'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=700&q=80','desc'=>'Jelajahi keindahan Sumbawa yang masih perawan.'],
            ['slug'=>'gili-islands','name'=>'Gili Islands Getaway','category'=>'Lombok','badge_class'=>'pkg-badge-lombok','duration'=>'3H / 2M','price'=>'Rp 1,8 Jt','img'=>'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=700&q=80','desc'=>'Nikmati keindahan tiga Gili yang ikonik.'],
            ['slug'=>'thailand-tour','name'=>'Thailand Grand Tour','category'=>'Luar Negeri','badge_class'=>'pkg-badge-intl','duration'=>'7H / 6M','price'=>'Rp 8,9 Jt','img'=>'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=700&q=80','desc'=>'Bangkok, Chiang Mai, dan Phuket dalam satu paket.'],
        ],
    ],

    'thailand-tour' => [
        'slug'=>'thailand-tour','name'=>'Thailand Grand Tour','category'=>'Luar Negeri','badge_class'=>'pkg-badge-intl','popular_badge'=>'🔥 Terpopuler',
        'location'=>'Bangkok, Chiang Mai, Phuket','duration'=>'7H / 6M','min_pax'=>2,'language'=>'Indonesia / Inggris / Thai',
        'rating'=>4.9,'reviews'=>201,'price_display'=>'Rp 8,9 Jt','price_raw'=>8900000,
        'hero_img'=>'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=1800&q=85',
        'desc'=>'Bangkok, Chiang Mai, dan Phuket dalam satu paket. Kuil megah, pasar apung, dan pantai Andaman yang jernih.',
        'desc_long'=>'Thailand Grand Tour adalah paket wisata internasional terlengkap yang mengajak Anda menjelajahi tiga kota ikonik Thailand — Bangkok yang dinamis, Chiang Mai yang tenang dengan budaya Lanna-nya, dan Phuket dengan pantai-pantai Andaman yang legendaris. Selama 7 hari 6 malam, rasakan keberagaman kuliner, arsitektur kuil yang memukau, pengalaman budaya yang autentik, dan alam bawah laut yang menakjubkan.',
        'map_embed'=>'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3875.573!2d100.523!3d13.736!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x311d6032280d61f3%3A0x10100b25de24820!2sBangkok!5e0!3m2!1sen!2sth!4v1',
        'gallery'=>['https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=1200&q=80','https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80','https://images.unsplash.com/photo-1562602834-1b4978d5e0ec?w=1200&q=80','https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80','https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=1200&q=80'],
        'highlights'=>[['icon'=>'fas fa-plane','title'=>'Tiket PP','sub'=>'Tiket penerbangan Lombok/Bali–Bangkok PP sudah termasuk'],['icon'=>'fas fa-hotel','title'=>'Hotel Bintang 4','sub'=>'Akomodasi 6 malam hotel bintang 4 di 3 kota'],['icon'=>'fas fa-user-tie','title'=>'Guide Berbahasa Indonesia','sub'=>'Pemandu wisata profesional berbahasa Indonesia'],['icon'=>'fas fa-ticket-alt','title'=>'Semua Tiket Masuk','sub'=>'Tiket masuk seluruh destinasi sudah termasuk']],
        'itinerary'=>[
            ['day'=>1,'title'=>'Tiba di Bangkok','desc'=>'Tiba di Bangkok dan eksplorasi kota.','activities'=>['Landing di Suvarnabhumi Airport','Transfer hotel & check-in','Chatuchak Weekend Market','Makan malam di Chinatown (Yaowarat)'],'note'=>'Penerbangan dari Lombok/Bali pagi hari'],
            ['day'=>2,'title'=>'Grand Palace & Chao Phraya','desc'=>'Jelajahi simbol-simbol kebudayaan Bangkok.','activities'=>['Wat Phra Kaew (Temple of Emerald Buddha)','Grand Palace','Wat Pho (Reclining Buddha)','River cruise Chao Phraya','Asiatique The Riverfront malam hari']],
            ['day'=>3,'title'=>'Bangkok — Chiang Mai','desc'=>'Pagi di Bangkok, siang terbang ke Chiang Mai.','activities'=>['Wat Arun (Temple of Dawn)','Pasar Chatuchak','Penerbangan Bangkok–Chiang Mai','Nimman Road Chiang Mai','Sunday Night Market']],
            ['day'=>4,'title'=>'Chiang Mai Cultural Day','desc'=>'Hari penuh budaya dan alam Chiang Mai.','activities'=>['Doi Inthanon National Park','Air terjun di Doi Inthanon','Doi Suthep Temple','Old City & Three Kings Monument','Khao Soi (kuliner khas)']],
            ['day'=>5,'title'=>'Chiang Mai — Phuket','desc'=>'Terbang ke Phuket dan nikmati pantai.','activities'=>['Penerbangan Chiang Mai–Phuket','Check-in resort di Patong/Kata','Pantai Kata & Karon','Bangla Road malam hari']],
            ['day'=>6,'title'=>'Island Hopping Phi Phi & Maya Bay','desc'=>'Full day island hopping ke destinasi ikonik.','activities'=>['Speedboat ke Phi Phi Islands','Maya Bay (The Beach)','Snorkeling di Viking Cave','Monkey Beach','Kembali ke Phuket — sunset Promthep Cape']],
            ['day'=>7,'title'=>'Phuket — Pulang','desc'=>'Pagi santai lalu terbang pulang.','activities'=>['Sarapan terakhir di resort','Big Buddha Phuket','Old Town Phuket','Transfer bandara','Penerbangan pulang ke Lombok/Bali'],'note'=>'Penerbangan pulang dari Phuket sore hari'],
        ],
        'includes'=>['Tiket pesawat PP Lombok/Bali–Bangkok + penerbangan domestik Thailand','Akomodasi 6 malam Hotel Bintang 4','Sarapan 6x','Transportasi AC selama tour','Speedboat island hopping Phi Phi','Guide berbahasa Indonesia','Semua tiket masuk destinasi','Air mineral','Bagasi kabin 7 kg + koper 20 kg'],
        'excludes'=>['Makan siang & malam (kecuali yang disebutkan)','Visa Thailand (free untuk WNI)','Tips guide & driver','Pengeluaran pribadi','Travel insurance (sangat disarankan)','Upgrade hotel'],
        'notes'=>['Paspor wajib masih berlaku minimal 6 bulan.','Thailand bebas visa untuk WNI hingga 30 hari.','Patuhi dress code saat mengunjungi kuil (tidak boleh berpakaian terbuka).'],
        'review_list'=>[
            ['name'=>'Fitri Handayani','date'=>'Mei 2025','rating'=>5,'text'=>'Thailand bersama WestTravel = terbaik! Guide-nya keren, semua destinasi wow. Maya Bay dan Phi Phi Islands nyata-nyata surga!'],
            ['name'=>'Eko Purnomo','date'=>'April 2025','rating'=>5,'text'=>'Paket internasional pertama saya, dan tidak kecewa sama sekali. Semua lancar, hotel bagus, dan guide-nya super sabar dan informatif.'],
            ['name'=>'Nita Sari','date'=>'Maret 2025','rating'=>5,'text'=>'Kuliner Thailand yang incredible, kuil-kuil yang megah, dan pantai yang indah — semua terwujud dalam 7 hari bersama WestTravel. 100% recommended!'],
        ],
        'related'=>[
            ['slug'=>'gili-islands','name'=>'Gili Islands Getaway','category'=>'Lombok','badge_class'=>'pkg-badge-lombok','duration'=>'3H / 2M','price'=>'Rp 1,8 Jt','img'=>'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=700&q=80','desc'=>'Nikmati keindahan tiga Gili yang ikonik.'],
            ['slug'=>'pulau-moyo','name'=>'Pulau Moyo Retreat','category'=>'Sumbawa','badge_class'=>'pkg-badge-sumbawa','duration'=>'3H / 2M','price'=>'Rp 3,5 Jt','img'=>'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=700&q=80','desc'=>'Glamping eksklusif di Pulau Moyo yang menakjubkan.'],
            ['slug'=>'pendakian-rinjani','name'=>'Pendakian Rinjani','category'=>'Lombok','badge_class'=>'pkg-badge-lombok','duration'=>'4H / 3M','price'=>'Rp 2,5 Jt','img'=>'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=700&q=80','desc'=>'Petualangan mendaki Gunung Rinjani yang legendaris.'],
        ],
    ],

    'senggigi-luxury-escape' => [
        'slug'          => 'senggigi-luxury-escape',
        'name'          => 'Senggigi Luxury Escape',
        'category'      => 'Lombok',
        'badge_class'   => 'pkg-badge-lombok',
        'popular_badge' => '💎 Premium',
        'location'      => 'Senggigi, Lombok',
        'duration'      => '5H / 4M',
        'min_pax'       => 2,
        'language'      => 'Indonesia / Inggris',
        'rating'        => 4.9,
        'reviews'       => 55,
        'price_display' => 'Rp 4,5 Jt',
        'price_raw'     => 4500000,
        'hero_img'      => 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1800&q=85',
        'desc'          => 'Pengalaman mewah di Senggigi dengan villa tepi pantai, spa, dan sunset cruise eksklusif.',
        'desc_long'     => 'Senggigi Luxury Escape dirancang khusus untuk Anda yang mendambakan liburan mewah dan eksklusif. Menginap di villa bintang 5 tepi pantai dengan pemandangan langsung ke Selat Lombok, nikmati layanan butler pribadi 24 jam, spa treatment premium, serta sunset cruise pribadi dengan yacht mewah. Paket ini sangat cocok untuk bulan madu, perayaan hari spesial, atau sekadar memanjakan diri dalam ketenangan.',
        'map_embed'     => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d31627.56!2d116.04!3d-8.48!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dcdc135f5c53fb3%3A0xc3cf97e6878b273d!2sSenggigi%2C%20Batu%20Layar%2C%20West%20Lombok%20Regency%2C%20West%20Nusa%20Tenggara!5e0!3m2!1sen!2sid!4v1',
        'gallery'       => [
            'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1200&q=80',
            'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=1200&q=80',
            'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200&q=80',
            'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=1200&q=80',
        ],
        'highlights'    => [
            ['icon' => 'fas fa-star', 'title' => 'Villa Bintang 5', 'sub' => 'Menginap di resort/villa bintang 5 terkemuka di Senggigi'],
            ['icon' => 'fas fa-spa', 'title' => 'Spa Treatment', 'sub' => 'Paket spa relaksasi 2 jam untuk pasangan'],
            ['icon' => 'fas fa-ship', 'title' => 'Sunset Cruise', 'sub' => 'Pelayaran pribadi menikmati sunset di atas yacht'],
            ['icon' => 'fas fa-concierge-bell', 'title' => 'Butler Service', 'sub' => 'Layanan butler pribadi 24 jam untuk segala keperluan Anda'],
        ],
        'itinerary'     => [
            [
                'day'        => 1,
                'title'      => 'Tiba & Check-in VIP',
                'desc'       => 'Penjemputan VIP di Bandara Lombok, check-in villa, romantic dinner.',
                'activities' => [
                    'Penjemputan VIP di Bandara Lombok dengan Toyota Alphard',
                    'Check-in di Pool Villa Bintang 5 Senggigi',
                    'Waktu santai menikmati fasilitas villa',
                    'Candlelight romantic dinner di pinggir pantai',
                ],
            ],
            [
                'day'        => 2,
                'title'      => 'Spa & Relaksasi Pasangan',
                'desc'       => 'Nikmati relaksasi spa mewah untuk memulihkan energi Anda.',
                'activities' => [
                    'Sarapan pagi ala carte di villa',
                    'Sesi couple spa treatment premium (2 jam) di resort',
                    'Makan siang sehat di tepi kolam',
                    'Free evening — menikmati sunset dari infinity pool',
                ],
            ],
            [
                'day'        => 3,
                'title'      => 'Private Sunset Cruise',
                'desc'       => 'Pelayaran eksklusif menikmati matahari terbenam di atas yacht.',
                'activities' => [
                    'Sarapan pagi dan waktu santai di villa',
                    'Makan siang romantis di pantai Senggigi',
                    'Naik yacht pribadi untuk Sunset Cruise (3 jam)',
                    'Makan malam mewah di atas yacht',
                ],
            ],
            [
                'day'        => 4,
                'title'      => 'Eksplorasi Senggigi & Pantai Utara',
                'desc'       => 'Mengunjungi spot budaya dan pantai eksotis di sekitar Senggigi.',
                'activities' => [
                    'Sarapan pagi di hotel',
                    'Mengunjungi Pura Batu Bolong yang bersejarah',
                    'Trekking ringan/jalan santai di pantai Senggigi',
                    'Menikmati teh sore di resort mewah terdekat',
                    'Makan malam di restoran fine dining lokal',
                ],
            ],
            [
                'day'        => 5,
                'title'      => 'Check-out & Transfer VIP',
                'desc'       => 'Sarapan terakhir sebelum penjemputan kembali ke bandara.',
                'activities' => [
                    'Sarapan pagi terakhir di villa',
                    'Check-out & pengantaran VIP ke Bandara Lombok',
                ],
            ],
        ],
        'includes'      => [
            'Penjemputan & transfer VIP Bandara PP (Toyota Alphard)',
            'Akomodasi 4 malam di Pool Villa Bintang 5',
            'Sarapan harian ala carte di villa',
            '1x Romantic Candlelight Dinner',
            'Private Yacht Sunset Cruise (3 jam) + Dinner',
            'Couple Spa Treatment (2 jam)',
            'Butler pribadi 24 jam',
            'Air mineral & welcome drink premium',
        ],
        'excludes'      => [
            'Tiket pesawat ke Lombok',
            'Makan siang & makan malam lainnya',
            'Tips guide & butler',
            'Pengeluaran pribadi',
        ],
        'notes'         => [
            'Pemesanan minimal 14 hari sebelum kedatangan.',
            'Harga berlaku untuk 2 orang (satu villa).',
            'Reschedule diperbolehkan maksimal 7 hari sebelum kedatangan.',
        ],
        'review_list'   => [
            ['name' => 'Rian Wijaya', 'date' => 'Mei 2025', 'rating' => 5, 'text' => 'Honeymoon yang luar biasa! Villa-nya sangat privat dan indah. Sunset cruise dengan yacht pribadi sangat berkesan. Pelayanan WestTravel top markotop!'],
            ['name' => 'Siska Lestari', 'date' => 'April 2025', 'rating' => 5, 'text' => 'Pelayanan bintang lima sesungguhnya. Butler sangat membantu dan ramah. Kamar menghadap laut dengan kolam pribadi. Sangat berharga.'],
        ],
        'related'       => [
            ['slug' => 'gili-islands', 'name' => 'Gili Islands Getaway', 'category' => 'Lombok', 'badge_class' => 'pkg-badge-lombok', 'duration' => '3H / 2M', 'price' => 'Rp 1,8 Jt', 'img' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=700&q=80', 'desc' => 'Nikmati keindahan tiga Gili yang ikonik.'],
            ['slug' => 'lombok-lengkap', 'name' => 'Lombok Lengkap Tour', 'category' => 'Lombok', 'badge_class' => 'pkg-badge-lombok', 'duration' => '5H / 4M', 'price' => 'Rp 3,2 Jt', 'img' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=700&q=80', 'desc' => 'Jelajahi Mandalika, Desa Sade, hingga tenun Sukarara.'],
            ['slug' => 'pulau-moyo', 'name' => 'Pulau Moyo Retreat', 'category' => 'Sumbawa', 'badge_class' => 'pkg-badge-sumbawa', 'duration' => '3H / 2M', 'price' => 'Rp 3,5 Jt', 'img' => 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=700&q=80', 'desc' => 'Glamping eksklusif dan diving di Pulau Moyo.'],
        ],
    ],

    'surfing-pantai-maluk' => [
        'slug'          => 'surfing-pantai-maluk',
        'name'          => 'Surfing Pantai Maluk',
        'category'      => 'Sumbawa',
        'badge_class'   => 'pkg-badge-sumbawa',
        'popular_badge' => null,
        'location'      => 'Maluk, Sumbawa Barat',
        'duration'      => '3H / 2M',
        'min_pax'       => 1,
        'language'      => 'Indonesia / Inggris',
        'rating'        => 4.5,
        'reviews'       => 38,
        'price_display' => 'Rp 2,2 Jt',
        'price_raw'     => 2200000,
        'hero_img'      => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1800&q=85',
        'desc'          => 'Rasakan ombak kelas dunia di Supersuck, Pantai Maluk. Surga para surfer dari seluruh penjuru dunia.',
        'desc_long'     => 'Paket Surfing Pantai Maluk mengajak Anda menantang ombak legendaris di Supersuck dan Pantai Maluk, Sumbawa Barat. Dikenal secara internasional memiliki barrel kiri yang panjang dan sempurna, kawasan ini adalah destinasi impian bagi para peselancar. Paket ini dirancang lengkap dengan akomodasi nyaman dekat pantai, sewa papan selancar, serta bimbingan dari instruktur lokal berpengalaman bagi yang ingin belajar atau meningkatkan kemampuan.',
        'map_embed'     => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d62744.13!2d116.78!3d-9.02!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dcc9c9c8dbeb7df%3A0xcb1b2e3f4a5b6c7d!2sMaluk%2C%20West%20Sumbawa%20Regency%2C%20West%20Nusa%20Tenggara!5e0!3m2!1sen!2sid!4v1',
        'gallery'       => [
            'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=1200&q=80',
            'https://images.unsplash.com/photo-1470246973918-29a93221c455?w=1200&q=80',
            'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80',
        ],
        'highlights'    => [
            ['icon' => 'fas fa-water', 'title' => 'Surfing Board', 'sub' => 'Pilihan papan selancar berkualitas sesuai tinggi dan berat badan'],
            ['icon' => 'fas fa-chalkboard-teacher', 'title' => 'Instruktur', 'sub' => 'Instruktur lokal bersertifikat untuk kelas pemula maupun menengah'],
            ['icon' => 'fas fa-home', 'title' => 'Penginapan Nyaman', 'sub' => 'Akomodasi surf camp/homestay nyaman di pinggir pantai Maluk'],
            ['icon' => 'fas fa-utensils', 'title' => 'Sarapan & Makan', 'sub' => 'Sarapan pagi sehat penunjang energi harian Anda'],
        ],
        'itinerary'     => [
            [
                'day'        => 1,
                'title'      => 'Tiba di Maluk & Pengenalan',
                'desc'       => 'Penjemputan di Pelabuhan Benete/Poto Tano, check-in, sesi perkenalan ombak sore hari.',
                'activities' => [
                    'Penjemputan di Pelabuhan Benete atau Poto Tano',
                    'Check-in di homestay/surf camp ber-AC',
                    'Fitting baju selancar dan pemilihan papan',
                    'Sesi pemanasan dan pengenalan pantai Maluk sore hari',
                ],
            ],
            [
                'day'        => 2,
                'title'      => 'Sesi Surfing Pagi & Lore',
                'desc'       => 'Latihan intensif pagi dan sore hari di spot surfing pilihan.',
                'activities' => [
                    'Sarapan pagi bergizi di homestay',
                    'Surfing sesi pagi didampingi instruktur (2-3 jam)',
                    'Makan siang dan istirahat',
                    'Surfing sesi sore di spot Supersuck (kondisional)',
                    'Makan malam santai bersama komunitas surfer lokal',
                ],
            ],
            [
                'day'        => 3,
                'title'      => 'Surfing Pagi & Check-out',
                'desc'       => 'Sesi surfing terakhir sebelum pengantaran pulang.',
                'activities' => [
                    'Sarapan pagi di homestay',
                    'Sesi surfing pagi terakhir untuk memantapkan teknik',
                    'Check-out dan transfer kembali ke Pelabuhan Benete/Poto Tano',
                ],
            ],
        ],
        'includes'      => [
            'Penjemputan & transfer dari Pelabuhan Benete/Poto Tano PP',
            'Akomodasi 2 malam di Surf Camp/Homestay ber-AC',
            'Sarapan pagi harian',
            'Sewa papan surfing selama 3 hari',
            'Instruktur selancar lokal (2 sesi per hari)',
            'Air mineral harian',
        ],
        'excludes'      => [
            'Transportasi menuju Sumbawa (tiket pesawat/kapal cepat)',
            'Makan siang & makan malam',
            'Pengeluaran pribadi',
            'Asuransi kecelakaan olahraga ekstrem',
        ],
        'notes'         => [
            'Olahraga surfing bergantung pada kondisi pasang surut dan arah angin.',
            'Bawa tabir surya tahan air (zinc) dan pelindung ruam (rash guard).',
            'Kategori pemula akan diarahkan ke spot dengan ombak lebih tenang.',
        ],
        'review_list'   => [
            ['name' => 'Fajar Nugraha', 'date' => 'Mei 2025', 'rating' => 5, 'text' => 'Supersuck gokil abis! Ombaknya panjang dan instruktur lokal tahu betul waktu terbaik untuk turun. Penginapannya santai dan nyaman.'],
            ['name' => 'Sarah Connor', 'date' => 'Maret 2025', 'rating' => 4, 'text' => 'Sangat menyenangkan belajar surfing di sini. Instrukturnya sabar banget ngajarin dasar-dasar berdiri di atas papan. Rekomendasi buat surfer pemula.'],
        ],
        'related'       => [
            ['slug' => 'sumbawa-paradise', 'name' => 'Sumbawa Hidden Paradise', 'category' => 'Sumbawa', 'badge_class' => 'pkg-badge-sumbawa', 'duration' => '4H / 3M', 'price' => 'Rp 2,8 Jt', 'img' => 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=700&q=80', 'desc' => 'Jelajahi keindahan Sumbawa yang masih perawan.'],
            ['slug' => 'pulau-moyo', 'name' => 'Pulau Moyo Retreat', 'category' => 'Sumbawa', 'badge_class' => 'pkg-badge-sumbawa', 'duration' => '3H / 2M', 'price' => 'Rp 3,5 Jt', 'img' => 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=700&q=80', 'desc' => 'Glamping eksklusif di Pulau Moyo yang menakjubkan.'],
            ['slug' => 'gili-islands', 'name' => 'Gili Islands Getaway', 'category' => 'Lombok', 'badge_class' => 'pkg-badge-lombok', 'duration' => '3H / 2M', 'price' => 'Rp 1,8 Jt', 'img' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=700&q=80', 'desc' => 'Nikmati keindahan tiga Gili yang ikonik.'],
        ],
    ],

    'jepang-sakura-tour' => [
        'slug'          => 'jepang-sakura-tour',
        'name'          => 'Jepang Sakura Tour',
        'category'      => 'Luar Negeri',
        'badge_class'   => 'pkg-badge-intl',
        'popular_badge' => '💎 Premium',
        'location'      => 'Tokyo, Kyoto, Osaka',
        'duration'      => '9H / 8M',
        'min_pax'       => 2,
        'language'      => 'Indonesia / Inggris / Jepang',
        'rating'        => 4.9,
        'reviews'       => 88,
        'price_display' => 'Rp 12,5 Jt',
        'price_raw'     => 12500000,
        'hero_img'      => 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1800&q=85',
        'desc'          => 'Saksikan keajaiban mekar bunga sakura di Tokyo, Kyoto, dan Osaka. Budaya, kuliner, dan alam Jepang dalam satu perjalanan.',
        'desc_long'     => 'Jepang Sakura Tour dirancang khusus untuk membawa Anda menyaksikan fenomena alam terindah di Jepang — mekarnya bunga sakura (hanami) yang magis. Selama 9 hari 8 malam, Anda akan diajak berkeliling kota megapolitan Tokyo, melintasi sejarah di kuil-kuil tradisional Kyoto, dan memanjakan lidah di pusat kuliner Osaka. Perjalanan semakin nyaman dengan tiket Shinkansen dan JR Pass 7 hari, serta pemandu wisata lokal berbahasa Indonesia.',
        'map_embed'     => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d103700.17!2d139.69!3d35.689!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60188b857628f87b%3A0xffffffff!2sTokyo%2C%20Japan!5e0!3m2!1sen!2sid!4v1',
        'gallery'       => [
            'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200&q=80',
            'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80',
            'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80',
            'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=1200&q=80',
        ],
        'highlights'    => [
            ['icon' => 'fas fa-plane', 'title' => 'Tiket PP', 'sub' => 'Tiket pesawat pulang-pergi kelas ekonomi (Lombok/Bali - Tokyo)'],
            ['icon' => 'fas fa-hotel', 'title' => 'Hotel Bintang 4+', 'sub' => 'Menginap di hotel bintang 4 dengan lokasi strategis dekat stasiun'],
            ['icon' => 'fas fa-subway', 'title' => 'JR Pass 7 Hari', 'sub' => 'Akses kereta cepat Shinkansen dan transportasi JR tanpa batas'],
            ['icon' => 'fas fa-user-tie', 'title' => 'Guide Lokal', 'sub' => 'Pemandu wisata profesional fasih bahasa Indonesia & Jepang'],
        ],
        'itinerary'     => [
            [
                'day'        => 1,
                'title'      => 'Keberangkatan & Tiba di Tokyo',
                'desc'       => 'Penerbangan dari Lombok/Bali menuju Bandara Haneda/Narita. Check-in hotel.',
                'activities' => [
                    'Penerbangan dari Lombok/Bali ke Tokyo',
                    'Penjemputan di bandara dan transfer ke hotel di Tokyo',
                    'Check-in hotel Bintang 4',
                ],
            ],
            [
                'day'        => 2,
                'title'      => 'Eksplorasi Tokyo Modern',
                'desc'       => 'Mengunjungi Shibuya Crossing, Harajuku, dan Shinjuku Gyoen.',
                'activities' => [
                    'Sarapan di hotel',
                    'Berfoto di Shibuya Crossing & Patung Hachiko',
                    'Berjalan-jalan di kawasan mode Harajuku',
                    'Menikmati keindahan sakura di Shinjuku Gyoen',
                    'Makan malam ramen khas Jepang',
                ],
            ],
            [
                'day'        => 3,
                'title'      => 'Tokyo Klasik & Senso-ji',
                'desc'       => 'Mengunjungi kuil tertua di Tokyo, Tokyo Skytree, dan belanja di Ginza.',
                'activities' => [
                    'Sarapan di hotel',
                    'Kuil Senso-ji (Asakusa) & belanja souvenir di Nakamise Street',
                    'Melihat Tokyo Skytree dari Sumida Park',
                    'Belanja produk premium di Ginza',
                ],
            ],
            [
                'day'        => 4,
                'title'      => 'Gunung Fuji & Danau Ashi',
                'desc'       => 'Melihat keindahan Gunung Fuji dikelilingi bunga sakura.',
                'activities' => [
                    'Perjalanan harian ke kawasan Fuji-Hakone',
                    'Cruise santai di Danau Ashi',
                    'Naik kereta gantung Hakone Ropeway',
                    'Melihat panorama Gunung Fuji dari stasiun 5 (jika cuaca mendukung)',
                ],
            ],
            [
                'day'        => 5,
                'title'      => 'Tokyo ke Kyoto dengan Shinkansen',
                'desc'       => 'Perjalanan cepat ke Kyoto dan mengunjungi Fushimi Inari Shrine.',
                'activities' => [
                    'Sarapan & check-out hotel',
                    'Naik kereta cepat Shinkansen menuju Kyoto (2.5 jam)',
                    'Check-in hotel di Kyoto',
                    'Mengunjungi kuil Fushimi Inari dengan ribuan gerbang Torii merah',
                ],
            ],
            [
                'day'        => 6,
                'title'      => 'Eksplorasi Budaya Tradisional Kyoto',
                'desc'       => 'Kunjungan kuil emas Kinkaku-ji, hutan bambu Arashiyama, dan Kiyomizu-dera.',
                'activities' => [
                    'Sarapan di hotel',
                    'Mengunjungi Kinkaku-ji (Golden Pavilion)',
                    'Jalan santai di hutan bambu Arashiyama',
                    'Kuil Kiyomizu-dera dengan pemandangan kota Kyoto dari atas panggung kayu',
                ],
            ],
            [
                'day'        => 7,
                'title'      => 'Kyoto ke Osaka & Kastil Osaka',
                'desc'       => 'Pindah ke Osaka, menjelajahi Kastil Osaka dan makan malam di Dotonbori.',
                'activities' => [
                    'Sarapan & check-out hotel',
                    'Menuju Osaka dengan kereta JR (30 menit)',
                    'Check-in hotel di Osaka',
                    'Mengunjungi Kastil Osaka yang dikelilingi ribuan pohon sakura',
                    'Wisata kuliner malam di Dotonbori & Shinsaibashi',
                ],
            ],
            [
                'day'        => 8,
                'title'      => 'Universal Studios Japan (USJ)',
                'desc'       => 'Seharian penuh bermain di salah satu theme park terbaik di dunia.',
                'activities' => [
                    'Sarapan di hotel',
                    'Eksplorasi seharian di Universal Studios Japan (opsional / waktu bebas untuk belanja)',
                ],
            ],
            [
                'day'        => 9,
                'title'      => 'Kepulangan ke Tanah Air',
                'desc'       => 'Check-out dan transfer ke bandara untuk penerbangan kembali.',
                'activities' => [
                    'Sarapan pagi terakhir & check-out hotel',
                    'Transfer ke Bandara Kansai (KIX)',
                    'Penerbangan kembali ke Lombok/Bali',
                ],
            ],
        ],
        'includes'      => [
            'Tiket pesawat internasional PP kelas ekonomi (Lombok/Bali ↔ Tokyo)',
            'Akomodasi 8 malam di Hotel Bintang 4',
            'Sarapan pagi harian di hotel',
            'JR Pass Ordinary 7 Hari',
            'Tiket masuk wisata sesuai itinerary',
            'Tour Guide profesional berbahasa Indonesia',
            'Bagasi kabin 7 kg + koper 20 kg',
        ],
        'excludes'      => [
            'Makan siang & malam (kecuali yang disebutkan)',
            'Biaya Visa Jepang (WNI pemegang e-paspor gratis registrasi visa)',
            'Tips guide & driver',
            'Pengeluaran pribadi',
            'Asuransi kecelakaan/travel',
        ],
        'notes'         => [
            'Paspor wajib berlaku minimal 6 bulan.',
            'Musim sakura berkisar dari akhir Maret hingga pertengahan April.',
            'Minimal booking 2 orang.',
        ],
        'review_list'   => [
            ['name' => 'Aditya Wibowo', 'date' => 'Mei 2025', 'rating' => 5, 'text' => 'Mimpi melihat sakura mekar terwujud! Kastil Osaka dikelilingi sakura pink indah sekali. Pelayanan guide sangat informatif.'],
            ['name' => 'Novi Lestari', 'date' => 'April 2025', 'rating' => 5, 'text' => 'Sangat teratur! Shinkansen nyaman, hotel dekat stasiun jadi tidak lelah berjalan. WestTravel merencanakannya dengan matang.'],
        ],
        'related'       => [
            ['slug' => 'thailand-tour', 'name' => 'Thailand Grand Tour', 'category' => 'Luar Negeri', 'badge_class' => 'pkg-badge-intl', 'duration' => '7H / 6M', 'price' => 'Rp 8,9 Jt', 'img' => 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=700&q=80', 'desc' => 'Bangkok, Chiang Mai, dan Phuket dalam satu paket.'],
            ['slug' => 'pulau-moyo', 'name' => 'Pulau Moyo Retreat', 'category' => 'Sumbawa', 'badge_class' => 'pkg-badge-sumbawa', 'duration' => '3H / 2M', 'price' => 'Rp 3,5 Jt', 'img' => 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=700&q=80', 'desc' => 'Glamping eksklusif di Pulau Moyo yang menakjubkan.'],
            ['slug' => 'gili-islands', 'name' => 'Gili Islands Getaway', 'category' => 'Lombok', 'badge_class' => 'pkg-badge-lombok', 'duration' => '3H / 2M', 'price' => 'Rp 1,8 Jt', 'img' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=700&q=80', 'desc' => 'Nikmati keindahan tiga Gili yang ikonik.'],
        ],
    ],
];

// ── Routes ──
Route::get('/', function () {
    return view('welcome');
});

Route::get('/packages', function () {
    return view('packages');
});

Route::get('/packages/{slug}', function ($slug) use ($packagesData) {
    if (!isset($packagesData[$slug])) {
        abort(404);
    }
    return view('package-detail', ['package' => $packagesData[$slug]]);
});
